export const ADD_USER = "ADD_USER";

export const FETCH_CARD_LIST = "FETCH_CARD_LIST";
export const FETCH_CARD_LIST_RESOLVE = "FETCH_CARD_LIST_RESOLVE";
export const FETCH_CARD_LIST_REJECT = "FETCH_CARD_LIST_REJECT";

export const FETCH_TEAM_USERS = "FETCH_TEAM_USERS";
export const FETCH_TEAM_USERS_RESOLVE = "FETCH_TEAM_USERS_RESOLVE";
export const FETCH_TEAM_USERS_REJECT = "FETCH_TEAM_USERS_REJECT";
